// <auto-generated />
using Back_end_task_list.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Back_end_task_list.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20240204191400_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("System.Threading.Tasks.Task", b =>
                {
                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
